# Generated by Django 5.0 on 2023-12-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='Image',
        ),
        migrations.AddField(
            model_name='store',
            name='image',
            field=models.ImageField(default='a', max_length=2083, upload_to=''),
            preserve_default=False,
        ),
    ]
